# Generated by Django 3.2.8 on 2021-11-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, default='static/img/default.jpg', upload_to='')),
                ('profession', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=6)),
                ('story', models.ManyToManyField(blank=True, to='portfolio.Story')),
            ],
        ),
    ]
