# Generated by Django 3.2.8 on 2021-11-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='story',
        ),
        migrations.AddField(
            model_name='user',
            name='story',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua', max_length=5000),
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
