# Generated by Django 3.2.8 on 2021-11-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_data',
            field=models.DateField(),
        ),
    ]
