# Generated by Django 3.2.8 on 2021-12-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='path',
        ),
        migrations.AddField(
            model_name='resume',
            name='raw_file',
            field=models.ImageField(blank=True, upload_to='resume/'),
        ),
    ]
