# Generated by Django 3.2.8 on 2021-11-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='path',
            field=models.FileField(upload_to='uploads/resume/'),
        ),
    ]
