# Generated by Django 3.2.8 on 2021-11-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211109_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='story',
        ),
        migrations.AddField(
            model_name='user',
            name='story',
            field=models.ManyToManyField(to='portfolio.Story'),
        ),
    ]
