# Generated by Django 3.2.8 on 2021-12-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211206_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='raw_file',
            field=models.ImageField(upload_to='resume/'),
        ),
    ]
