# Generated by Django 3.2.8 on 2021-11-10 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20211110_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story',
            new_name='text',
        ),
    ]
