# Generated by Django 3.2.8 on 2021-11-10 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20211110_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Black Magic', max_length=30)),
                ('percentage', models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.ManyToManyField(to='portfolio.Skill'),
        ),
    ]
