# Generated by Django 3.2.8 on 2021-11-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20211110_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_from', models.DateField()),
                ('work_to', models.DateField()),
                ('position', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('task', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', max_length=1000)),
            ],
        ),
    ]
