# Generated by Django 3.2.8 on 2021-11-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_user_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_data',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/img/default.jpg', upload_to=''),
        ),
    ]
