# Generated by Django 3.2.8 on 2021-11-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Job',
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.ManyToManyField(to='portfolio.Job'),
        ),
    ]
