# Generated by Django 3.2.8 on 2021-11-10 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20211110_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='work_to',
            new_name='work_till',
        ),
    ]
