# Generated by Django 3.2.8 on 2021-11-10 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_rename_work_to_job_work_till'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='description',
        ),
    ]
