# Generated by Django 3.2.8 on 2021-11-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_rename_task_task_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-work_from']},
        ),
    ]
