# Generated by Django 3.2.8 on 2021-11-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_job_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_from', models.DateField()),
                ('study_till', models.DateField()),
                ('certificate', models.CharField(max_length=100)),
                ('authority', models.CharField(max_length=100)),
                ('current', models.BooleanField(default=False)),
                ('study', models.ManyToManyField(to='portfolio.Study')),
            ],
        ),
    ]
