# Generated by Django 3.2.8 on 2021-11-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_job_work_till'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-study_from']},
        ),
    ]
