# Generated by Django 3.2.8 on 2021-11-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_certificate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='study_till',
            field=models.DateField(blank=True),
        ),
    ]
