# Generated by Django 3.2.8 on 2021-11-24 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_project_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='portfolio.user'),
            preserve_default=False,
        ),
    ]
