# Generated by Django 3.2.8 on 2021-11-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_project_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ManyToManyField(to='portfolio.User'),
        ),
    ]
