# Generated by Django 3.2.8 on 2021-11-24 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_auto_20211124_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
    ]
