# Generated by Django 3.2.8 on 2021-11-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_auto_20211124_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(to='portfolio.Project'),
        ),
    ]
