# Generated by Django 3.2.8 on 2021-11-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_user_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='projects',
            new_name='project',
        ),
    ]
